name: Terraform_AWS_CICD_MyResmue
on: [push, pull_request,workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}

jobs:  
  Test:
    name: Validate Website Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --global prettier

      - name: Format files
        run: prettier --write .         


  infra:
    name: Provision My WebSite on AWS infrastructure using Terraform
    runs-on: ubuntu-latest
    needs: [Test]
    outputs:
      eip: ${{ steps.MyVPC.outputs.ec2_address }}

    environment: ${{ github.event.inputs.environment }}
    env:
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
    
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan

      
      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: Get Instance IP
        id: ip
        run: |
          terraform-bin output -raw instance_public_ip > ip_address.txt
          echo "ec2_address=$(cat ip_address.txt)" >> $GITHUB_OUTPUT

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ steps.ip.outputs.ec2_address }}
          username: ec2-user
          port: 22
          key: ${{ secrets.SSH_KEY_PATH }}
          source: index.html
          target: /home/ec2-user/

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.ip.outputs.ec2_address }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY_PATH }}
          port: 22
          script: |
            
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            sudo mv index.html /var/www/html
            
